version: '3.9'

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app # (!) Use backslashes (\) for Windows when running through `docker run`
    command: >
      sh -c 'python manage.py runserver 0.0.0.0:8000'
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=admin
    depends_on:
      - db
  
  db:
    image: postgres:16.1-alpine3.17
    volumes:
      - dev-db-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=admin

volumes:
  dev-db-data: