# Generated by Django 4.2.7 on 2023-12-07 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
