# Generated by Django 4.2.7 on 2023-12-07 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_user_is_staff_user_is_stiffler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_stiffler',
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
