# Generated by Django 4.2.7 on 2023-12-07 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
