# Generated by Django 4.2.7 on 2023-12-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
