# Generated by Django 4.2.8 on 2023-12-21 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_tag_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='days',
            field=models.CharField(max_length=255),
        ),
    ]
