# Generated by Django 4.2.8 on 2023-12-21 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_tag_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='days',
        ),
    ]
