# Generated by Django 4.2.8 on 2023-12-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_recipe_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.ManyToManyField(blank=True, to='core.tag'),
        ),
    ]
