# Generated by Django 4.2.8 on 2023-12-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_recipe_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.TextField(default='lalala'),
            preserve_default=False,
        ),
    ]
