# Generated by Django 4.2.8 on 2023-12-23 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_tag_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='description',
        ),
    ]
