# Generated by Django 4.2.8 on 2023-12-23 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_tag_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
