# Generated by Django 4.2.9 on 2024-01-02 18:13

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_recipe_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='lalala', upload_to=core.models.generate_recipe_image_path),
            preserve_default=False,
        ),
    ]
